### ISSUE TITLE
Inconsistent behaviour for "Duplicate global keys found" depending on dataset size

### ISSUE THREAD

**Issue by mtandy1** [Labelbox/labelbox-python#1249]
**The situation:** You're uploading a 500-1500 data rows with `task = dataset.create_data_rows(labelbox_assets)`

Duplicate global keys are rare, but they happen occasionally, as a colleague might have already sent a given asset for labelling. So you have perhaps one or two rows with duplicate global keys.

**The issue:** The python API behaves differently depending on (as far as I can tell) where in the dataset the duplicates are.

* If the dataset is smaller, or the duplicate is near the start, no rows are added to the dataset, `task.errors` returns a string ("Duplicate global keys found...") and accessing `task.result` raises an error.
* If the dataset is larger and the duplicate is near the end, some rows are added to the dataset, `task.errors` returns a list of dicts, with `task.errors[0]['message']` containing "Duplicate global keys found..." and `task.result` returns a list of the rows that were successfully added to the dataset.

I haven't taken the time to determine precisely what values count as 'larger' and 'near the end' but when I tried to upload a dataset of 1310 rows and encountered this problem, 310 were added to the dataset and 1000 weren't.

Needless to say, for users who respond to duplicate global keys by removing the duplicates and retrying, the current behaviour is confusing. For one behaviour, accessing `task.result` is impossible, while for the other it's required for your retry to succeed.

**Comment by Gabefire** [comment]
Hey @mtandy1 , 
So I tested this, and it could be that the behavior has changed since October, but it stops processing data rows the moment in the data set it hits a duplicate key, so if it is at the beginning, no data rows will be uploaded. I did this on a 10k dataset and had the dup in the middle, and it stopped adding data rows at that point. I also did something similar for a smaller dataset, 100 data rows. In both cases, I can access the `task.results`. This is intentional as we would not want to waste a lot of time looping through the dataset to validate no duplicates and then loop again to upload the data rows. To avoid this obvious, it is best to ensure no duplicate keys on your end, but you could else use `task.failed_data_rows` to find the point it failed and pick up your progress from there after you change the global key.

Thanks,
Gabe
