### ISSUE TITLE
`project.label_generator` breaks for empty segmentation annotation

### ISSUE THREAD

**Issue by felixdorrek** [Labelbox/labelbox-python#335]
Context:
- Image assets without file-extension 
- Ontology consisting of segmentation and global classification
- There exist non-skipped labels without any segmentation annotation

Behaviour:
- `project.label_generator()` fails with `Unexpected exception while filling the queue. TypeError("Can't infer data type from row data. Remove empty examples before trying again.`

Exception is thrown here:
https://github.com/Labelbox/labelbox-python/blob/8e11ab8afb5332a6a3c186b593d498bf4100c815/labelbox/data/serialization/labelbox_v1/label.py#L207

The comment partially documents the behaviour - however from a user perspective this fails on valid not-skipped labels.

**Comment by msokoloff1** [comment]
Thanks for the description we will take a look.

**Comment by msokoloff1** [comment]
There is no way to know the type without passing in extra information. Since we are discussing adding these types internally, I don't want to create a workaround that we have to remove in the near term. I added an extra field called media_type that any future solution can leverage. For now it will enable an ugly workaround to unblock you.

You can do the following:
```
json_labels = project.export_labels(download = True)
for row in json_labels:
    row['media_type'] = 'image'

labels = LBV1Converter.deserialize(payload)
```
I am going to close this for now. Feel free to open if you have any problems or questions.
