### ISSUE TITLE
Transparent fill for bounding box

### ISSUE THREAD

**Issue by michaelwants** [Labelbox/labelbox-python#396]
Hi all, I'm trying to label a series of images using labelbox, and am unable to find a way to make the fill inside each box transparent. I am able to reduce the intensity/opacity of the fill, but cannot remove it completely.

Does anyone know how to achieve this effect?

Cheers,

Michael

<img width="1540" alt="Screen Shot 2022-01-16 at 7 18 42 am" src="https://user-images.githubusercontent.com/96816689/149637238-a64d0694-7d7b-454f-95b6-558949c834a8.png">

**Comment by msokoloff1** [comment]
There isn't a great library for automatically drawing transparent overlays. Basically you want to take the weighted average of the pixels in the background and the bounding box pixels to create the opacity effect. Here is a decent article on how to do this:
https://www.pyimagesearch.com/2016/03/07/transparent-overlays-with-opencv/

I am going to close this issue because it isn't a problem with the SDK.
