### ISSUE TITLE
ModuleNotFoundError: No module named 'labelbox.client'; 'labelbox' is not a package

### ISSUE THREAD

**Issue by swirlingsand** [Labelbox/labelbox-python#46]
```
>>> import labelbox
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\play\labelbox.py", line 2, in <module>
    from labelbox.client import Client
ModuleNotFoundError: No module named 'labelbox.client'; 'labelbox' is not a package
>>> exit()

>>>pip show labelbox
Name: labelbox
Version: 2.4.4
Summary: Labelbox Python API
Home-page: https://labelbox.com
Author: Labelbox
Author-email: engineering@labelbox.com
License: UNKNOWN
Location: c:\programdata\miniconda3\lib\site-packages
Requires: ndjson, requests, backoff
Required-by:
```

**Comment by rllin** [comment]
I'd suggest reading about how `sys.path` in Python works [0] this will be helpful in general for your Python journey

you are getting this error because you've named your file `labelbox.py` and you are likely inside the directory `C:\play`

python (by default, i.e. if you don't change your `sys.path`) will check for imports in this order:

1. local path
2. directories specified by `PYTHONPATH`
3. those installed by your package manager, e.g. `pip`

[0] https://docs.python.org/3/library/sys.html#sys.path
